# Quarkus Configuration Properties
quarkus.http.port=8089
quarkus.http.test-port=8089

# Custom properties
hr.database.file-path=data/employees.md
%test.hr.database.file-path=target/test-employees.md

# Log settings
quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{3.}] (%t) %s%e%n
quarkus.log.level=INFO
